export const managerAbi = [
  {
    type: "function",
    name: "EXECUTOR_FEE_BPS",
    inputs: [],
    outputs: [{ type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "feeRecipient",
    inputs: [],
    outputs: [{ type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "createPlan",
    inputs: [
      { name: "token", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "period", type: "uint256" },
    ],
    outputs: [{ name: "planId", type: "bytes32" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "protocolFeeBps",
    inputs: [],
    outputs: [{ type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "protocolFlatFee",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "executorFeeBps",
    inputs: [],
    outputs: [{ type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setProtocolFeeBps",
    inputs: [{ name: "_bps", type: "uint16" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setProtocolFlatFee",
    inputs: [{ name: "_fee", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setExecutorFeeBps",
    inputs: [{ name: "_bps", type: "uint16" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "deactivatePlan",
    inputs: [{ name: "planId", type: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "subscribe",
    inputs: [
      { name: "planId", type: "bytes32" },
      { name: "totalSpendCap", type: "uint256" },
    ],
    outputs: [{ name: "subscriptionId", type: "bytes32" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancel",
    inputs: [{ name: "subscriptionId", type: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "charge",
    inputs: [{ name: "subscriptionId", type: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getPlan",
    inputs: [{ name: "planId", type: "bytes32" }],
    outputs: [
      {
        type: "tuple",
        components: [
          { name: "merchant", type: "address" },
          { name: "token", type: "address" },
          { name: "amount", type: "uint256" },
          { name: "period", type: "uint256" },
          { name: "active", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getSubscription",
    inputs: [{ name: "subscriptionId", type: "bytes32" }],
    outputs: [
      {
        type: "tuple",
        components: [
          { name: "customer", type: "address" },
          { name: "merchant", type: "address" },
          { name: "token", type: "address" },
          { name: "amount", type: "uint256" },
          { name: "period", type: "uint256" },
          { name: "nextChargeAt", type: "uint256" },
          { name: "totalSpendCap", type: "uint256" },
          { name: "totalSpent", type: "uint256" },
          { name: "active", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "computeSubId",
    inputs: [
      { name: "planId", type: "bytes32" },
      { name: "customer", type: "address" },
    ],
    outputs: [{ type: "bytes32" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "getMerchantStats",
    inputs: [{ name: "merchant", type: "address" }],
    outputs: [
      {
        type: "tuple",
        components: [
          { name: "totalEarned",   type: "uint256" },
          { name: "totalFeesPaid", type: "uint256" },
          { name: "totalCharges",  type: "uint256" },
          { name: "activePlans",   type: "uint256" },
          { name: "activeSubs",    type: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "PlanCreated",
    inputs: [
      { name: "planId", type: "bytes32", indexed: true },
      { name: "merchant", type: "address", indexed: true },
      { name: "token", type: "address", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
      { name: "period", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlanDeactivated",
    inputs: [
      { name: "planId", type: "bytes32", indexed: true },
      { name: "merchant", type: "address", indexed: true },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Subscribed",
    inputs: [
      { name: "subscriptionId", type: "bytes32", indexed: true },
      { name: "planId", type: "bytes32", indexed: true },
      { name: "customer", type: "address", indexed: true },
      { name: "totalSpendCap", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ChargeExecuted",
    inputs: [
      { name: "subscriptionId", type: "bytes32", indexed: true },
      { name: "executor", type: "address", indexed: true },
      { name: "customer", type: "address", indexed: true },
      { name: "gross", type: "uint256", indexed: false },
      { name: "merchantAmount", type: "uint256", indexed: false },
      { name: "executorFee", type: "uint256", indexed: false },
      { name: "protocolFee", type: "uint256", indexed: false },
      { name: "nextChargeAt", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Cancelled",
    inputs: [
      { name: "subscriptionId", type: "bytes32", indexed: true },
      { name: "caller", type: "address", indexed: true },
    ],
    anonymous: false,
  },
] as const;

export const payrollAbi = [
  {
    type: "function",
    name: "createPlan",
    inputs: [
      { name: "token", type: "address" },
      { name: "period", type: "uint256" },
    ],
    outputs: [{ name: "planId", type: "bytes32" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "deactivatePlan",
    inputs: [{ name: "planId", type: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addRecipient",
    inputs: [
      { name: "planId", type: "bytes32" },
      { name: "wallet", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "spendCap", type: "uint256" },
    ],
    outputs: [{ name: "recipientId", type: "bytes32" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addRecipientsBatch",
    inputs: [
      { name: "planId", type: "bytes32" },
      { name: "wallets", type: "address[]" },
      { name: "amounts", type: "uint256[]" },
      { name: "spendCaps", type: "uint256[]" },
    ],
    outputs: [{ name: "recipientIds", type: "bytes32[]" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "removeRecipient",
    inputs: [
      { name: "planId", type: "bytes32" },
      { name: "recipientId", type: "bytes32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateRecipient",
    inputs: [
      { name: "planId", type: "bytes32" },
      { name: "recipientId", type: "bytes32" },
      { name: "newAmount", type: "uint256" },
      { name: "newSpendCap", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "executePayroll",
    inputs: [
      { name: "planId", type: "bytes32" },
      { name: "recipientId", type: "bytes32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "executePayrollBatch",
    inputs: [
      { name: "planId", type: "bytes32" },
      { name: "recipientIds", type: "bytes32[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getRecipient",
    inputs: [
      { name: "planId", type: "bytes32" },
      { name: "recipientId", type: "bytes32" },
    ],
    outputs: [
      {
        type: "tuple",
        components: [
          { name: "wallet", type: "address" },
          { name: "amount", type: "uint256" },
          { name: "nextPayAt", type: "uint256" },
          { name: "totalPaid", type: "uint256" },
          { name: "spendCap", type: "uint256" },
          { name: "active", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPlanRecipients",
    inputs: [{ name: "planId", type: "bytes32" }],
    outputs: [
      {
        type: "tuple[]",
        components: [
          { name: "wallet", type: "address" },
          { name: "amount", type: "uint256" },
          { name: "nextPayAt", type: "uint256" },
          { name: "totalPaid", type: "uint256" },
          { name: "spendCap", type: "uint256" },
          { name: "active", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDueRecipients",
    inputs: [{ name: "planId", type: "bytes32" }],
    outputs: [{ type: "bytes32[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPlanRecipientIds",
    inputs: [{ name: "planId", type: "bytes32" }],
    outputs: [{ type: "bytes32[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "computeRecipientId",
    inputs: [
      { name: "planId", type: "bytes32" },
      { name: "wallet", type: "address" },
    ],
    outputs: [{ type: "bytes32" }],
    stateMutability: "pure",
  },
  {
    type: "event",
    name: "PlanCreated",
    inputs: [
      { name: "planId", type: "bytes32", indexed: true },
      { name: "employer", type: "address", indexed: true },
      { name: "token", type: "address", indexed: false },
      { name: "period", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlanDeactivated",
    inputs: [
      { name: "planId", type: "bytes32", indexed: true },
      { name: "employer", type: "address", indexed: true },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RecipientAdded",
    inputs: [
      { name: "planId", type: "bytes32", indexed: true },
      { name: "recipientId", type: "bytes32", indexed: true },
      { name: "wallet", type: "address", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
      { name: "spendCap", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RecipientRemoved",
    inputs: [
      { name: "planId", type: "bytes32", indexed: true },
      { name: "recipientId", type: "bytes32", indexed: true },
      { name: "removedBy", type: "address", indexed: true },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RecipientUpdated",
    inputs: [
      { name: "planId", type: "bytes32", indexed: true },
      { name: "recipientId", type: "bytes32", indexed: true },
      { name: "newAmount", type: "uint256", indexed: false },
      { name: "newSpendCap", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PayrollExecuted",
    inputs: [
      { name: "planId", type: "bytes32", indexed: true },
      { name: "recipientId", type: "bytes32", indexed: true },
      { name: "executor", type: "address", indexed: true },
      { name: "recipient", type: "address", indexed: false },
      { name: "grossAmount", type: "uint256", indexed: false },
      { name: "recipientAmount", type: "uint256", indexed: false },
      { name: "executorFee", type: "uint256", indexed: false },
      { name: "protocolFee", type: "uint256", indexed: false },
      { name: "nextPayAt", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "BatchPayrollExecuted",
    inputs: [
      { name: "planId", type: "bytes32", indexed: true },
      { name: "executor", type: "address", indexed: true },
      { name: "successCount", type: "uint256", indexed: false },
      { name: "failCount", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
] as const;

export const erc20Abi = [
  {
    type: "function",
    name: "balanceOf",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "allowance",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "approve",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "mint",
    inputs: [
      { name: "to", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "decimals",
    inputs: [],
    outputs: [{ type: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "symbol",
    inputs: [],
    outputs: [{ type: "string" }],
    stateMutability: "view",
  },
] as const;
