export const managerAbi = [
  {
    type: "function",
    name: "EXECUTOR_FEE_BPS",
    inputs: [],
    outputs: [{ type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "feeRecipient",
    inputs: [],
    outputs: [{ type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "createPlan",
    inputs: [
      { name: "token", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "period", type: "uint256" },
    ],
    outputs: [{ name: "planId", type: "bytes32" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "protocolFeeBps",
    inputs: [],
    outputs: [{ type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "protocolFlatFee",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "executorFeeBps",
    inputs: [],
    outputs: [{ type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setProtocolFeeBps",
    inputs: [{ name: "_bps", type: "uint16" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setProtocolFlatFee",
    inputs: [{ name: "_fee", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setExecutorFeeBps",
    inputs: [{ name: "_bps", type: "uint16" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "deactivatePlan",
    inputs: [{ name: "planId", type: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "subscribe",
    inputs: [
      { name: "planId", type: "bytes32" },
      { name: "totalSpendCap", type: "uint256" },
    ],
    outputs: [{ name: "subscriptionId", type: "bytes32" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancel",
    inputs: [{ name: "subscriptionId", type: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "chargeFor",
    inputs: [
      { name: "subscriptionId", type: "bytes32" },
      { name: "executorFeeBpsOverride", type: "uint16" },
      { name: "executorPayee", type: "address" },
    ],
    outputs: [
      { name: "grossAmount", type: "uint256" },
      { name: "executorFeePaid", type: "uint256" },
      { name: "protocolFeePaid", type: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "trustedExecutor",
    inputs: [],
    outputs: [{ type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setTrustedExecutor",
    inputs: [{ name: "newExecutor", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getPlan",
    inputs: [{ name: "planId", type: "bytes32" }],
    outputs: [
      {
        type: "tuple",
        components: [
          { name: "merchant", type: "address" },
          { name: "token", type: "address" },
          { name: "amount", type: "uint256" },
          { name: "period", type: "uint256" },
          { name: "active", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getSubscription",
    inputs: [{ name: "subscriptionId", type: "bytes32" }],
    outputs: [
      {
        type: "tuple",
        components: [
          { name: "customer", type: "address" },
          { name: "merchant", type: "address" },
          { name: "token", type: "address" },
          { name: "amount", type: "uint256" },
          { name: "period", type: "uint256" },
          { name: "nextChargeAt", type: "uint256" },
          { name: "totalSpendCap", type: "uint256" },
          { name: "totalSpent", type: "uint256" },
          { name: "active", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "computeSubId",
    inputs: [
      { name: "planId", type: "bytes32" },
      { name: "customer", type: "address" },
    ],
    outputs: [{ type: "bytes32" }],
    stateMutability: "pure",
  },
  {
    type: "event",
    name: "PlanCreated",
    inputs: [
      { name: "planId", type: "bytes32", indexed: true },
      { name: "merchant", type: "address", indexed: true },
      { name: "token", type: "address", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
      { name: "period", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlanDeactivated",
    inputs: [
      { name: "planId", type: "bytes32", indexed: true },
      { name: "merchant", type: "address", indexed: true },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Subscribed",
    inputs: [
      { name: "subscriptionId", type: "bytes32", indexed: true },
      { name: "planId", type: "bytes32", indexed: true },
      { name: "customer", type: "address", indexed: true },
      { name: "totalSpendCap", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ChargeExecuted",
    inputs: [
      { name: "subscriptionId", type: "bytes32", indexed: true },
      { name: "executor", type: "address", indexed: true },
      { name: "customer", type: "address", indexed: true },
      { name: "gross", type: "uint256", indexed: false },
      { name: "merchantAmount", type: "uint256", indexed: false },
      { name: "executorFee", type: "uint256", indexed: false },
      { name: "protocolFee", type: "uint256", indexed: false },
      { name: "nextChargeAt", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Cancelled",
    inputs: [
      { name: "subscriptionId", type: "bytes32", indexed: true },
      { name: "caller", type: "address", indexed: true },
    ],
    anonymous: false,
  },
] as const;

export const payrollAbi = [
  {
    type: "function",
    name: "createPlan",
    inputs: [
      { name: "token", type: "address" },
      { name: "period", type: "uint256" },
    ],
    outputs: [{ name: "planId", type: "bytes32" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "deactivatePlan",
    inputs: [{ name: "planId", type: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addRecipient",
    inputs: [
      { name: "planId", type: "bytes32" },
      { name: "wallet", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "spendCap", type: "uint256" },
    ],
    outputs: [{ name: "recipientId", type: "bytes32" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addRecipientsBatch",
    inputs: [
      { name: "planId", type: "bytes32" },
      { name: "wallets", type: "address[]" },
      { name: "amounts", type: "uint256[]" },
      { name: "spendCaps", type: "uint256[]" },
    ],
    outputs: [{ name: "recipientIds", type: "bytes32[]" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "removeRecipient",
    inputs: [
      { name: "planId", type: "bytes32" },
      { name: "recipientId", type: "bytes32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateRecipient",
    inputs: [
      { name: "planId", type: "bytes32" },
      { name: "recipientId", type: "bytes32" },
      { name: "newAmount", type: "uint256" },
      { name: "newSpendCap", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "executePayrollFor",
    inputs: [
      { name: "planId", type: "bytes32" },
      { name: "recipientId", type: "bytes32" },
      { name: "executorFeeBpsOverride", type: "uint16" },
      { name: "executorPayee", type: "address" },
    ],
    outputs: [
      { name: "grossAmount", type: "uint256" },
      { name: "executorFeePaid", type: "uint256" },
      { name: "protocolFeePaid", type: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "executePayrollBatchFor",
    inputs: [
      { name: "planId", type: "bytes32" },
      { name: "recipientIds", type: "bytes32[]" },
      { name: "executorFeeBpsOverride", type: "uint16" },
      { name: "executorPayee", type: "address" },
    ],
    outputs: [
      { name: "totalExecutorFee", type: "uint256" },
      { name: "totalProtocolFee", type: "uint256" },
      { name: "successCount", type: "uint256" },
      { name: "failCount", type: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "trustedExecutor",
    inputs: [],
    outputs: [{ type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setTrustedExecutor",
    inputs: [{ name: "newExecutor", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getPlanRecipients",
    inputs: [{ name: "planId", type: "bytes32" }],
    outputs: [
      {
        type: "tuple[]",
        components: [
          { name: "wallet", type: "address" },
          { name: "amount", type: "uint256" },
          { name: "nextPayAt", type: "uint256" },
          { name: "totalPaid", type: "uint256" },
          { name: "spendCap", type: "uint256" },
          { name: "active", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDueRecipients",
    inputs: [{ name: "planId", type: "bytes32" }],
    outputs: [{ type: "bytes32[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPlanRecipientIds",
    inputs: [{ name: "planId", type: "bytes32" }],
    outputs: [{ type: "bytes32[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "computeRecipientId",
    inputs: [
      { name: "planId", type: "bytes32" },
      { name: "wallet", type: "address" },
    ],
    outputs: [{ type: "bytes32" }],
    stateMutability: "pure",
  },
  {
    type: "event",
    name: "PlanCreated",
    inputs: [
      { name: "planId", type: "bytes32", indexed: true },
      { name: "employer", type: "address", indexed: true },
      { name: "token", type: "address", indexed: false },
      { name: "period", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlanDeactivated",
    inputs: [
      { name: "planId", type: "bytes32", indexed: true },
      { name: "employer", type: "address", indexed: true },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RecipientAdded",
    inputs: [
      { name: "planId", type: "bytes32", indexed: true },
      { name: "recipientId", type: "bytes32", indexed: true },
      { name: "wallet", type: "address", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
      { name: "spendCap", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RecipientRemoved",
    inputs: [
      { name: "planId", type: "bytes32", indexed: true },
      { name: "recipientId", type: "bytes32", indexed: true },
      { name: "removedBy", type: "address", indexed: true },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RecipientUpdated",
    inputs: [
      { name: "planId", type: "bytes32", indexed: true },
      { name: "recipientId", type: "bytes32", indexed: true },
      { name: "newAmount", type: "uint256", indexed: false },
      { name: "newSpendCap", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PayrollExecuted",
    inputs: [
      { name: "planId", type: "bytes32", indexed: true },
      { name: "recipientId", type: "bytes32", indexed: true },
      { name: "executor", type: "address", indexed: true },
      { name: "recipient", type: "address", indexed: false },
      { name: "grossAmount", type: "uint256", indexed: false },
      { name: "recipientAmount", type: "uint256", indexed: false },
      { name: "executorFee", type: "uint256", indexed: false },
      { name: "protocolFee", type: "uint256", indexed: false },
      { name: "nextPayAt", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "BatchPayrollExecuted",
    inputs: [
      { name: "planId", type: "bytes32", indexed: true },
      { name: "executor", type: "address", indexed: true },
      { name: "successCount", type: "uint256", indexed: false },
      { name: "failCount", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
] as const;

// ─── PulseExecutor ABI ───────────────────────────────────────────────────────
// Keep this in lockstep with /contracts/src/PulseExecutor.sol.

export const executorAbi = [
  // Keeper entrypoints
  {
    type: "function",
    name: "execute",
    inputs: [{ name: "paymentId", type: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "executeBatch",
    inputs: [{ name: "paymentIds", type: "bytes32[]" }],
    outputs: [],
    stateMutability: "nonpayable",
  },

  // Views
  {
    type: "function",
    name: "computePaymentId",
    inputs: [
      { name: "manager", type: "address" },
      { name: "innerId", type: "bytes32" },
    ],
    outputs: [{ type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPayment",
    inputs: [{ name: "paymentId", type: "bytes32" }],
    outputs: [
      {
        type: "tuple",
        components: [
          { name: "kind",        type: "uint8"   }, // 0=Subscription, 1=Payroll
          { name: "manager",     type: "address" },
          { name: "planId",      type: "bytes32" },
          { name: "innerId",     type: "bytes32" },
          { name: "scheduledAt", type: "uint64"  },
          { name: "period",      type: "uint64"  },
          { name: "registered",  type: "bool"    },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getStats",
    inputs: [{ name: "executor", type: "address" }],
    outputs: [
      {
        type: "tuple",
        components: [
          { name: "totalExecutions",        type: "uint128" },
          { name: "successfulExecutions",   type: "uint128" },
          { name: "failedExecutions",       type: "uint128" },
          { name: "totalVolumeProcessed",   type: "uint128" },
          { name: "totalFeesEarned",        type: "uint128" },
          { name: "averageExecutionDelay",  type: "uint64"  },
          { name: "lastExecutionTimestamp", type: "uint64"  },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "dynamicFeeBps",
    inputs: [{ name: "delaySeconds", type: "uint256" }],
    outputs: [{ type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isRestricted",
    inputs: [{ name: "executor", type: "address" }],
    outputs: [{ type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "failureRateBps",
    inputs: [{ name: "executor", type: "address" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MIN_FEE_BPS",
    inputs: [],
    outputs: [{ type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_FEE_BPS",
    inputs: [],
    outputs: [{ type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "RAMP_DURATION",
    inputs: [],
    outputs: [{ type: "uint64" }],
    stateMutability: "view",
  },

  // Errors
  { type: "error", name: "PaymentNotRegistered", inputs: [{ name: "paymentId",   type: "bytes32" }] },
  { type: "error", name: "PaymentNotDue",        inputs: [{ name: "paymentId",   type: "bytes32" }, { name: "scheduledAt", type: "uint256" }] },
  { type: "error", name: "ExecutorRestricted",   inputs: [{ name: "executor",    type: "address" }] },
  { type: "error", name: "BatchEmpty",           inputs: [] },
  { type: "error", name: "PausedError",          inputs: [] },

  // Events
  {
    type: "event",
    name: "PaymentRegistered",
    inputs: [
      { name: "paymentId",   type: "bytes32", indexed: true },
      { name: "manager",     type: "address", indexed: true },
      { name: "kind",        type: "uint8",   indexed: false },
      { name: "planId",      type: "bytes32", indexed: false },
      { name: "innerId",     type: "bytes32", indexed: false },
      { name: "scheduledAt", type: "uint64",  indexed: false },
      { name: "period",      type: "uint64",  indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PaymentDeregistered",
    inputs: [
      { name: "paymentId", type: "bytes32", indexed: true },
      { name: "manager",   type: "address", indexed: true },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ExecutionSucceeded",
    inputs: [
      { name: "paymentId",       type: "bytes32", indexed: true },
      { name: "executor",        type: "address", indexed: true },
      { name: "grossAmount",     type: "uint256", indexed: false },
      { name: "executorReward",  type: "uint256", indexed: false },
      { name: "withheld",        type: "uint256", indexed: false },
      { name: "bpsApplied",      type: "uint16",  indexed: false },
      { name: "delaySeconds",    type: "uint64",  indexed: false },
      { name: "nextScheduledAt", type: "uint64",  indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ExecutionFailed",
    inputs: [
      { name: "paymentId",  type: "bytes32", indexed: true },
      { name: "executor",   type: "address", indexed: true },
      { name: "reasonHash", type: "bytes32", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "BatchExecuted",
    inputs: [
      { name: "executor",     type: "address", indexed: true },
      { name: "successCount", type: "uint256", indexed: false },
      { name: "failCount",    type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
] as const;

export const erc20Abi = [
  {
    type: "function",
    name: "balanceOf",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "allowance",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "approve",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "mint",
    inputs: [
      { name: "to", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "decimals",
    inputs: [],
    outputs: [{ type: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "symbol",
    inputs: [],
    outputs: [{ type: "string" }],
    stateMutability: "view",
  },
] as const;
